algorithm: iomatch
save_dir: ./saved_models/openset_cv
resume: True
save_name: iomatch_test_dns_extra_ep250_bs256
load_path: ./saved_models/openset_cv/iomatch_test_dns_extra_ep250_bs256/7499_model.pth
overwrite: True
use_tensorboard: True
epoch: 250
num_train_iter: 25000
batch_size: 256
num_eval_iter: 100
num_labels: 2500
eval_batch_size: 32
p_cutoff: 0.95
q_cutoff: 0.5
ulb_loss_ratio: 1.0
dist_align: False
uratio: 7
ema_m: 0.999
crop_ratio:  0
img_size: [16,16]
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_10_2
net_from_name: False
data_dir: ./data
dataset: merge_month_2_4_dns_openset
train_sampler: RandomSampler
num_classes: 25
num_workers: 0
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None
